version: '3.8'

services:
  node-app:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        npm run prisma:deploy
        npm run dev
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - "${PORT}:${PORT}"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
          ignore:
            - node_modules
        - action: rebuild
          path: package.json

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    hostname: ${POSTGRES_HOST}
    command: -p ${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "/usr/bin/pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -h ${POSTGRES_HOST}"
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    
